apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: email-newsletter
  description: Production grade test API
  annotations:
    github.com/project-slug: DerekCrosson/email-newsletter
  tags:
    - rust
spec:
  type: api
  lifecycle: production
  owner: derekcrosson18@gmail.com
  definition:
    $text: https://github.com/DerekCrosson/email-newsletter/docs
